/*
 * The Egg language constitutes of words, values and applications.
 *
 * words have names, which are bound to program constructs. The names can be
 * any character except \s, (, ), [,], ".
 *
 * values can be either strings or digits. String values can be any character
 * except ". Digit values have one or more digits.
 *
 * applications have operator that refers to the expression being applied and
 * args that refer to the arguments that this expression operates upon
 *
 * The following is an example Egg program.
 */
var testExpr = 
  'do(define(x, 10),' +
    'if(>(x, 5),' +
      'print("large"),' +
      'print("small")))'


/*
 * The parser creates the following structure from an egg program:
 * {
 *   type: 'apply',
 *   operator: { type: 'word', name: <word_name> },
 *   args: [
 *     { type: 'word', name: <word_name> },
 *     { type: 'value', value: <value> }
 *   ]
 * }
 */
var skipSpace = function (str) {
  var idx = str.search(/\S/)
  if (idx === -1) return ''
  str = str.slice(idx)
  while (str[0] === '#') {
    idx = str.search(/(\n|\r\n?)/) + 1
    str = str.slice(idx)
    idx = str.search(/\S/)
    str = str.slice(idx)
  }

  return str
}

function parseApply(expr, program) {
  program = skipSpace(program)
  if (program[0] !== '(') {
    return { tree: expr, rest: program }
  }

  program = skipSpace(program.slice(1))
  expr = { type: 'apply', operator: expr, args: [] }
  while (program[0] !== ')') {
    var arg = parseExpression(program)
    expr.args.push(arg.tree)
    program = skipSpace(arg.rest)
    if (program[0] === ',') {
      program = skipSpace(program.slice(1))
    } else if (program[0] !== ')') {
      throw new SyntaxError("Expected ',' or ')'")
    }
  }
  return parseApply(expr, program.slice(1))
}

function parseExpression(program) {
  program = skipSpace(program)
  var match
  var expr
  if (match = /^"([^"]*)"/.exec(program)) {
    expr = { type: 'value', value: match[1] }
  } else if (match = /^\d+\b/.exec(program)) {
    expr = { type: 'value', value: Number(match[0]) }
  } else if (match = /^[^\s(),"]+/.exec(program)) {
    expr = { type: 'word', name: match[0] }
  } else {
    throw new SyntaxError("Unexpected syntax: " + program)
  }

  return parseApply(expr, program.slice(match[0].length))
}

var parse = function (program) {
  var parsed = parseExpression(program)
  if (skipSpace(parsed.rest).length > 0) {
    throw new SyntaxError('Unexpected text after program: ' + parsed.rest)
  }
  return parsed.tree
}

/*
 * The evaluator uses the tree generated by the parser to evaluate an Egg
 * program.
 */
var evaluate = function (expr, env) {
  switch (expr.type) {
    case 'value':
      return expr.value

    case 'word':
      if (expr.name in env) {
        return env[expr.name]
      } else {
        throw new ReferenceError('Undefined variable: ' + expr.name)
      }

    case 'apply':
      if (expr.operator.type === 'word' &&
          expr.operator.name in specialForms) {
        return specialForms[expr.operator.name](expr.args, env)
      }

      var op = evaluate(expr.operator, env)
      if (typeof op !== 'function') {
        throw new TypeError('Applying to non-function')
      }
      return op.apply(null, expr.args.map(function (arg) {
        return evaluate(arg, env)
      }))
  }
}

var specialForms = Object.create(null)
specialForms['if'] = function (args, env) {
  if (args.length !== 3) {
    throw new SyntaxError('Expected 3 arguments to if')
  }

  if (evaluate(args[0], env) === true) {
    return evaluate(args[1], env)
  } else {
    return evaluate(args[2], env)
  }
}

specialForms['while'] = function (args, env) {
  if (args.length !== 2) {
    throw new SyntaxError('Expected 2 arguments to while')
  }

  while (evaluate(args[0], env) !== false) {
    evaluate(args[1], env)
  }
  return false
}

specialForms['do'] = function (args, env) {
  var result = false
  args.forEach(function (arg) {
    result = evaluate(arg, env)
  })
  return result
}

specialForms['define'] = function (args, env) {
  if (args.length !== 2) {
    throw new SyntaxError('Expected 2 arguments to define')
  }

  var word = args[0]
  if (word.type !== 'word') {
    throw new SyntaxError('Expected a word as the first argument to define')
  }

  var value = evaluate(args[1], env)
  env[word.name] = value
  return value
}

specialForms['fun'] = function (args, env) {
  if (!args.length) {
    throw new SyntaxError('Functions need a body')
  }
  var name = function (expr) {
    if (expr.type !== 'word') {
      throw new SyntaxError('Arg names must be words')
    }
    return expr.name
  }
  var argNames = args.slice(0, args.length - 1).map(name)
  var body = args[args.length - 1]

  return function () {
    if (arguments.length !== argNames.length) {
      throw new SyntaxError('Wrong number of arguments')
    }
    var localEnv = Object.create(env)
    for (var i = 0; i < arguments.length; i++) {
      localEnv[argNames[i]] = arguments[i]
    }
    return evaluate(body, localEnv)
  }
}

var topEnv = {
  'true': true,
  'false': false,
  'print': function (value) {
    console.log(value)
    return value
  }
}

var ops = ['+', '-', '*', '/', '==', '<', '>']
ops.forEach(function (op) {
  topEnv[op] = new Function('a, b', 'return a ' + op + ' b;')
})

/* Array support */
topEnv['array'] = function () {
  return Array.prototype.slice.call(arguments, 0)
}

topEnv['length'] = function (array) {
  return array.length
}

topEnv['element'] = function (array, n) {
  return array[n]
}

var run = function () {
  var env = Object.create(topEnv)
  var program = Array.prototype.slice.call(arguments, 0).join('\n')
  return evaluate(parse(program), env)
}


var plusOne = 'do(define(plusOne, fun (a, +(a, 1))),' +
              '  print(plusOne(10)))'

var pow = 'do(define(pow, fun (base, exp,' +
          '  if(==(exp, 0),' +
          '     1,' +
          '     *(base, pow(base, -(exp, 1)))))),' +
          '  print(pow(2, 10)))'

var arr = 'do(define(sum, fun(array,\n' +
          '     do(define(i, 0),\n' +
          '        define(sum, 0),\n' +
          '        while(<(i, length(array)),\n' +
          '          do(define(sum, +(sum, element(array, i))),\n' +
          '             define(i, +(i, 1)))),\n' +
          '        sum))),\n' +
          '   # print("sad"),\n' +
          '   print(sum(array(1, 2, 3))))'

var closure = 'do(define(f, fun(a, fun(b, +(a, b)))),' +
              '  print(f(4)(5)))'

console.log(parse("# hello\nx"))

console.log(parse("a # one\n   # two\n()"))

console.log(parse(arr))
run(plusOne)
